#sudo: required

services:
  - docker

language: java

before_script:
  - bash ./.travis/sauce_connect.sh #open Sauce connector

script:
  - ./gradlew build

after_success:
  - sh ./.travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false" && sh .travis/deploy_heroku.sh