sudo: required

services:
  - docker

language: python

python:
  - "2.7"

addons:
  sauce_connect: true

before_script:
  - python app.py & #launch the server in the background to allow selenium testing
  - sleep 3 # give application some time to start

script:
  - python -m pytest -v

after_success:
  - sh ./.travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false" && sh .travis/deploy_heroku.sh