sudo: required

services:
  - docker


language: python

python:
  - "2.7"

script:
  - python -m pytest -v -k "not TestBrowserBehaviour"

after_success:
  - sh ./.travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false" && sh .travis/deploy_heroku.sh